// 200+ Motivational Quotes for Productivity

export const motivationalQuotes = [
  // Success & Achievement (30 quotes)
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future depends on what you do today.",
  "Your limitation—it's only your imagination.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It's going to be hard, but hard does not mean impossible.",
  "Don't wait for opportunity. Create it.",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "Your only limit is you.",
  "Sometimes later becomes never. Do it now.",
  "The secret of getting ahead is getting started.",
  "Success is the sum of small efforts repeated day in and day out.",
  "You don't have to be great to start, but you have to start to be great.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "You are never too old to set another goal or to dream a new dream.",
  "Opportunities don't happen, you create them.",
  "Try not to become a person of success, but rather a person of value.",
  "Innovation distinguishes between a leader and a follower.",
  
  // Focus & Productivity (40 quotes)
  "Focus on being productive instead of busy.",
  "The way to get started is to quit talking and begin doing.",
  "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.",
  "Productivity is never an accident. It is always the result of a commitment to excellence.",
  "Either you run the day, or the day runs you.",
  "Until we can manage time, we can manage nothing else.",
  "Time is what we want most, but what we use worst.",
  "The most effective way to do it, is to do it.",
  "Action is the foundational key to all success.",
  "You don't need a new plan for next year. You need a commitment.",
  "The only impossible journey is the one you never begin.",
  "Start where you are. Use what you have. Do what you can.",
  "Everything you've ever wanted is on the other side of fear.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "Don't be afraid to give up the good to go for the great.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success seems to be connected with action. Successful people keep moving.",
  "The distance between insanity and genius is measured only by success.",
  "Don't be distracted by criticism. Remember—the only taste of success some people get is to take a bite out of you.",
  "What you do today can improve all your tomorrows.",
  "The way to get things done is not to mind who gets the credit for doing them.",
  "If you are working on something that you really care about, you don't have to be pushed.",
  "People who are crazy enough to think they can change the world, are the ones who do.",
  "Failure will never overtake me if my determination to succeed is strong enough.",
  "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
  "We may encounter many defeats but we must not be defeated.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "With the new day comes new strength and new thoughts.",
  "Either write something worth reading or do something worth writing.",
  "Nothing is impossible. The word itself says 'I'm possible!'",
  "The only place where success comes before work is in the dictionary.",
  "Too many of us are not living our dreams because we are living our fears.",
  "I didn't fail the test. I just found 100 ways to do it wrong.",
  "A person who never made a mistake never tried anything new.",
  "Today's accomplishments were yesterday's impossibilities.",
  "The only person you are destined to become is the person you decide to be.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Everything has beauty, but not everyone can see.",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
  "Life is really simple, but we insist on making it complicated.",
  
  // Perseverance & Growth (40 quotes)
  "Fall seven times and stand up eight.",
  "A year from now you may wish you had started today.",
  "You are never too old to set another goal or to dream a new dream.",
  "The secret of change is to focus all of your energy not on fighting the old, but on building the new.",
  "Courage is resistance to fear, mastery of fear—not absence of fear.",
  "We generate fears while we sit. We overcome them by action.",
  "Whether you think you can or think you can't, you're right.",
  "Security is mostly a superstition. Life is either a daring adventure or nothing.",
  "The man who has confidence in himself gains the confidence of others.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't limit yourself. Many people limit themselves to what they think they can do.",
  "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
  "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Change your thoughts and you change your world.",
  "The most common way people give up their power is by thinking they don't have any.",
  "The mind is everything. What you think you become.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "An unexamined life is not worth living.",
  "Eighty percent of success is showing up.",
  "Your time is limited, so don't waste it living someone else's life.",
  "Winning isn't everything, but wanting to win is.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "Every child is an artist. The problem is how to remain an artist once he grows up.",
  "You can never cross the ocean until you have the courage to lose sight of the shore.",
  "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
  "Whether you think you can or you think you can't, you're right.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.",
  "The best revenge is massive success.",
  "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.",
  "Life shrinks or expands in proportion to one's courage.",
  "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
  "Do what you can with all you have, wherever you are.",
  "You take your life in your own hands, and what happens? A terrible thing, no one to blame.",
  "If you're offered a seat on a rocket ship, don't ask what seat! Just get on.",
  "I learned that courage was not the absence of fear, but the triumph over it.",
  "I alone cannot change the world, but I can cast a stone across the water to create many ripples.",
  
  // Time Management (30 quotes)
  "Time is the most valuable thing a man can spend.",
  "Lost time is never found again.",
  "Time flies over us, but leaves its shadow behind.",
  "Better three hours too soon than a minute too late.",
  "Time is what we want most, but what we use worst.",
  "The bad news is time flies. The good news is you're the pilot.",
  "Time is more valuable than money. You can get more money, but you cannot get more time.",
  "Don't say you don't have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo da Vinci, Thomas Jefferson, and Albert Einstein.",
  "Your time is limited, don't waste it living someone else's life.",
  "The key is in not spending time, but in investing it.",
  "Time you enjoy wasting is not wasted time.",
  "Time = life; therefore, waste your time and waste of your life, or master your time and master your life.",
  "Until you value yourself, you won't value your time. Until you value your time, you will not do anything with it.",
  "Time is the wisest counselor of all.",
  "Time is the longest distance between two places.",
  "Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin.",
  "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.'",
  "The trouble is, you think you have time.",
  "One day or day one. You decide.",
  "How you spend your time is how you spend your life.",
  "Time is the coin of your life. It is the only coin you have, and only you can determine how it will be spent.",
  "Make use of time, let not advantage slip.",
  "The common man is not concerned about the passage of time, the man of talent is driven by it.",
  "Time stays long enough for anyone who will use it.",
  "Time is free, but it's priceless. You can't own it, but you can use it.",
  "One worthwhile task carried to a successful conclusion is worth half-a-hundred half-finished tasks.",
  "He who every morning plans the transactions of that day and follows that plan carries a thread that will guide him through the labyrinth of the most busy life.",
  "Don't wait. The time will never be just right.",
  "Time management is life management.",
  "The shorter way to do many things is to only do one thing at a time.",

  // Goals & Planning (30 quotes)
  "A goal without a plan is just a wish.",
  "Setting goals is the first step in turning the invisible into the visible.",
  "You are never too old to set another goal or to dream a new dream.",
  "The trouble with not having a goal is that you can spend your life running up and down the field and never score.",
  "A goal properly set is halfway reached.",
  "If you want to be happy, set a goal that commands your thoughts, liberates your energy and inspires your hopes.",
  "Goals are dreams with deadlines.",
  "By recording your dreams and goals on paper, you set in motion the process of becoming the person you most want to be.",
  "Our goals can only be reached through a vehicle of a plan, in which we must fervently believe, and upon which we must vigorously act.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The greater danger for most of us lies not in setting our aim too high and falling short; but in setting our aim too low, and achieving our mark.",
  "You should set goals beyond your reach so you always have something to live for.",
  "A dream written down with a date becomes a goal. A goal broken down into steps becomes a plan.",
  "All who have accomplished great things have had a great aim, have fixed their gaze on a goal which was high, one which sometimes seemed impossible.",
  "The most important thing about goals is having one.",
  "Goals allow you to control the direction of change in your favor.",
  "Goals are not only absolutely necessary to motivate us. They are essential to really keep us alive.",
  "If you don't know where you are going, you'll end up someplace else.",
  "The only impossible journey is the one you never begin.",
  "People with goals succeed because they know where they're going.",
  "You don't have to see the whole staircase, just take the first step.",
  "Goals transform a random walk into a chase.",
  "The goal is not to be better than the other man, but your previous self.",
  "Set your goals high, and don't stop till you get there.",
  "Obstacles are those frightful things you see when you take your eyes off your goal.",
  "Without goals, and plans to reach them, you are like a ship that has set sail with no destination.",
  "Goals are the fuel in the furnace of achievement.",
  "Review your goals twice every day in order to be focused on achieving them.",
  "I don't focus on what I'm up against. I focus on my goals and I try to ignore the rest.",
  "Arriving at one goal is the starting point to another.",

  // Motivation & Inspiration (30 quotes)
  "The only way to achieve the impossible is to believe it is possible.",
  "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.",
  "I learned that courage was not the absence of fear, but the triumph over it.",
  "You are capable of more than you know. Choose a goal that seems right for you and strive to be the best, however hard the path.",
  "If you can dream it, you can do it.",
  "You were born to be a player. You were meant to be here. This moment is yours.",
  "Life is like riding a bicycle. To keep your balance, you must keep moving.",
  "Do not wait to strike till the iron is hot; but make it hot by striking.",
  "Fortune favors the bold.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "It is during our darkest moments that we must focus to see the light.",
  "Believe you can and you're halfway there.",
  "Just one small positive thought in the morning can change your whole day.",
  "The only impossible journey is the one you never begin.",
  "Inspiration does exist, but it must find you working.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "If opportunity doesn't knock, build a door.",
  "Live life to the fullest, and focus on the positive.",
  "The power of imagination makes us infinite.",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
  "In the middle of every difficulty lies opportunity.",
  "Learn from yesterday, live for today, hope for tomorrow.",
  "You miss 100% of the shots you don't take.",
  "Turn your wounds into wisdom.",
  "Change your life today. Don't gamble on the future, act now, without delay.",
  "Every strike brings me closer to the next home run.",
  "It always seems impossible until it's done.",
  "Don't let yesterday take up too much of today.",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character.",
  "If you're going through hell, keep going."
];

export const getRandomQuote = (): string => {
  return motivationalQuotes[Math.floor(Math.random() * motivationalQuotes.length)];
};

export const getDailyQuote = (): string => {
  // Get a consistent quote for the day based on date
  const today = new Date().toDateString();
  const hash = today.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  return motivationalQuotes[hash % motivationalQuotes.length];
};