// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soxtmznhpmbsndjcuhse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNveHRtem5ocG1ic25kamN1aHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NjczNDUsImV4cCI6MjA3MTE0MzM0NX0.EtnjtduJTnwmmmf4TeRyiG6zOQU_ntTXo94cXPng2ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});